Mail pulls
Readarr/Readarr pull request #1093
Opened 2021-07-01 04:00 UTC by bakerboy448

#### Database Migration
YES - 13 MailSettings

#### Description
Various pulls; primarily mail related

#### Screenshot (if UI related)

#### Todos
- Tests
-  Wiki Updates

#### Issues Fixed or Closed by this PR

* Closes #981
* Closes #980
* Closes #982
* Fixes #854
* Fixes #884
* Fixes #951
* Fixes #954
* Closes #723

2021-07-01 04:07 UTC, Qstick requested changes

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core.Test/Datastore/Migration/013_email_multiple_addressesFixture.cs
> +    public class EmailSettings48
EmailSettings12

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core.Test/Datastore/Migration/013_email_multiple_addressesFixture.cs
> +    public class EmailSettings49
EmailSettings13

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core/Datastore/Migration/013_email_multiple_addresses.cs
> +        private class EmailSettings48
EmailSettings12

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core/Datastore/Migration/013_email_multiple_addresses.cs
> +        private class EmailSettings49
EmailSettings13

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core.Test/Datastore/Migration/013_email_multiple_addressesFixture.cs
> +        public bool OnTrackRetag { get; set; }
OnBookRetag

Ref. https://github.com/Readarr/Readarr/blob/8406dbe49de5b06e0ec8dfad46c1b2575c4dff74/src/NzbDrone.Core/Notifications/NotificationBase.cs#L63

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core.Test/Datastore/Migration/013_email_multiple_addressesFixture.cs
> +                    OnTrackRetag = true,
OnBookRetag

Ref. https://github.com/Readarr/Readarr/blob/8406dbe49de5b06e0ec8dfad46c1b2575c4dff74/src/NzbDrone.Core/Notifications/NotificationBase.cs#L63

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core/Notifications/Email/Email.cs
> -            var paths = Settings.AttachFiles ? message.BookFiles.SelectList(a => a.Path) : null;
We don't want to drop this

2021-07-01 04:07 UTC, Qstick commented on src/NzbDrone.Core/Datastore/Migration/013_email_multiple_addresses.cs
> +using System;
To seems to already be a string[] on Readarr? If so we don't need the migration

Ref.
https://github.com/Readarr/Readarr/blob/8406dbe49de5b06e0ec8dfad46c1b2575c4dff74/src/NzbDrone.Core/Notifications/Email/EmailSettings.cs#L52

2021-07-01 04:21 UTC, Qstick requested changes, later dismissed

2021-07-01 04:21 UTC, Qstick commented on src/NzbDrone.Core/Notifications/Email/Email.cs
> +            SendEmail(Settings, BOOK_DOWNLOADED_TITLE_BRANDED, body);
You need update this to accept the attachment paths, like the old method

2021-07-01 04:21 UTC, Qstick commented on src/NzbDrone.Core/Readarr.Core.csproj
> +    <PackageReference Include="MailKit" Version="2.10.1" />
Drop the version number to fix build.

2021-07-01 04:42 UTC, Qstick commented
Didn’t know ta added Directory.Package.Props to centralize package versions, you need to add Malikit ref there as well

2021-07-01 05:08 UTC, bakerboy448 commented
- [ ] ToDo: Figure out MailKit attachment handling and correct Email.cs as needed

2021-07-01 05:10 UTC, bakerboy448 commented on src/NzbDrone.Core/Notifications/Email/Email.cs
> +                    email.Attachments.Add(new MimePart(url));
specifically; figure this out

2021-07-01 20:30 UTC, bakerboy448 commented on src/NzbDrone.Core/Notifications/Email/Email.cs
> +                    email.Attachments.Add(new MimePart(url));
http://www.mimekit.net/docs/html/P_MimeKit_MimeMessage_Attachments.htm
and
http://www.mimekit.net/docs/html/Creating-Messages.htm

2021-07-02 00:01 UTC, bakerboy448 commented
Attachments work; tested locally with blackhole for an import.

We may want to somehow guard and set a size limit?

2021-07-02 00:15 UTC, RobinDadswell commented
Take a look at this, I think we should try and guard on size by checking the maximum size from a capabilities check 

http://www.mimekit.net/docs/html/P_MailKit_Net_Smtp_SmtpClient_MaxSize.htm

2021-07-02 02:56 UTC, bakerboy448 commented
> Take a look at this, I think we should try and guard on size by checking the maximum size from a capabilities check
> 
> http://www.mimekit.net/docs/html/P_MailKit_Net_Smtp_SmtpClient_MaxSize.htm

agreed  we'd also need to know the proposed attachment(s) sizes to check against

How should we handle a multiple part book where only 1 of the parts is under the size limit?

(also way out of my depth here)

2021-07-02 07:39 UTC, RobinDadswell commented
We shouldn't be handling it on a per attachment basis but on the size of the whole mail. I'll try have a look later today

2021-07-03 01:15 UTC, Qstick approved these changes

2021-07-03 01:16 UTC, merged