Corrected naming examples
Readarr/Readarr pull request #1096
Opened 2021-07-01 22:29 UTC by PearsonFlyer

#### Database Migration
NO

#### Description
Corrected naming examples in Media Management modal.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

* Fixes #1091

2021-07-01 22:34 UTC, bakerboy448 requested changes

2021-07-01 22:34 UTC, bakerboy448 commented on frontend/src/Settings/MediaManagement/Naming/NamingModal.js
> +  { token: '{Author Name}', example: 'Author's Name' },
escape the `'` like `\'`

ref https://github.com/Radarr/Radarr/commit/b06ec1f291f90dbfcaf155847af991d7bf7af4cb

2021-07-01 23:54 UTC, bakerboy448 approved these changes

2021-07-01 23:55 UTC, bakerboy448 commented
Wiki Updates :) https://wiki.servarr.com/readarr/settings

2021-07-01 23:55 UTC, merged

2021-07-02 00:15 UTC, PearsonFlyer commented
Wiki updated.