Fixed: failing test if exe is missing
Readarr/Readarr pull request #1099
Opened 2021-07-02 12:16 UTC by PearsonFlyer

#### Database Migration
NO

#### Description
Properly fails update test if the Readarr.Update.exe is missing.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

* Fixes #860

2021-07-02 12:17 UTC, ta264 commented
This probably needs Sonarr -> Radarr

2021-07-02 23:28 UTC, Qstick requested changes

2021-07-02 23:28 UTC, Qstick commented on src/NzbDrone.Core.Test/UpdateTests/UpdatePackageProviderFixture.cs
> +        [Ignore("Ignore until we actually release something on Main")]
Master

2021-07-02 23:28 UTC, Qstick commented on src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
> +        public string Branch => GetValue("Branch", "main").ToLowerInvariant();
Master

2021-07-02 23:28 UTC, Qstick commented on src/NzbDrone.Core/Configuration/DeploymentInfoProvider.cs
> +            DefaultBranch = "main";
Master

2021-07-02 23:28 UTC, Qstick commented on src/NzbDrone.Core/Update/InstallUpdateService.cs
> +
No double blank

2021-07-02 23:28 UTC, Qstick commented on src/NzbDrone.Core/Update/InstallUpdateService.cs
> +        public void Handle(ApplicationStartingEvent message)
Need to add the file for ApplicationStartingEvent

2021-07-04 15:00 UTC, bakerboy448 commented
@PearsonFlyer wrong branch pushed here?

2021-07-08 03:29 UTC, closed without merging