New: Various Healthcheck enhancements
Readarr/Readarr pull request #1328
Opened 2021-11-15 00:13 UTC by bakerboy448

New: Localized HealthChecks
Fixed: Healthcheck Wiki Links
Various pulls from Radarr;  Completed at the file - not commit - level

#### Database Migration
NO

#### Description
- Brings over numerous Radarr commits for healthchecks including correct strings and previously missed localizations
- Builds
- Tests (almost) all work

#### Screenshot (if UI related)

#### Todos
- [ ] Tests **Need some help fixing the broken ImportList healthcheck; I'm not seeing it**
- [X] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json) - Added some; likely missing some though. also noticed unused strings exist @austinwbest cleanup in aisle translate json? :D
- [ ] [Wiki Updates](https://wiki.servarr.com) - @RobinDadswell we did all the wikis right?

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2021-11-15 20:01 UTC, RobinDadswell submitted a review, later dismissed

2021-11-15 20:01 UTC, RobinDadswell commented on src/NzbDrone.Core.Test/HealthCheck/Checks/AppDataLocationFixture.cs
> +
Add this to the fixture of the failing test and it should start working again for you

2021-12-03 10:32 UTC, ta264 commented
> Various pulls from Radarr; Completed at the file - not commit - level

@bakerboy448 if you're going to do that, can you add in the PR `- Fixed #xxx` for each pull issue you've covered with this?

2021-12-03 14:42 UTC, bakerboy448 commented
@ta264 there are no Radarr Pull issues to tag.

By radarr pulls I mean various (upwards of a dozen I think) radarr commits that we're never commoned and thus never pulled.

2022-01-19 17:37 UTC, ta264 requested changes
Looks like a bunch of the translations you reference are missing.  eg IndexerStatusCheckAllClientMessage

2022-01-19 18:25 UTC, ta264 approved these changes

2022-01-19 18:47 UTC, merged