Added lastSearchTime to wanted-screens
Readarr/Readarr pull request #3724
Opened 2024-09-09 12:35 UTC by ManiMatter

Fixes https://github.com/Readarr/Readarr/issues/3709

Note: When I try to manually import PDFs in my local instance, I get errors like the following, which seem to be somehow related to an authentication problem.
`Could not load source './Readarr.Host/Bootstrap.cs': Incorrect format of 'source' message..`

If I skip these errors, it works.

The same errors also come up in the version without my commits, thus I believe it's not related to what I added.

2024-09-13 20:17 UTC, ManiMatter commented
@mynameisbogdan - would you have an idea what is causing this?

2024-12-11 12:13 UTC, ManiMatter commented
Can this be merged?

2025-01-09 00:09 UTC, mynameisbogdan requested changes

2025-01-09 00:09 UTC, mynameisbogdan commented on src/Readarr.Api.V1/Books/BookResource.cs
> +                LastSearchTime = resource.LastSearchTime
This should be removed from the ToModel.

2025-01-09 19:57 UTC, ManiMatter commented on src/Readarr.Api.V1/Books/BookResource.cs
> +                LastSearchTime = resource.LastSearchTime
Done that and rebased to latest commit of develop-branch.

However, now I get two problems
1) When running locally, I see
`Readarr/src/NzbDrone.Common/Readarr.Common.csproj : error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Microsoft.SourceLink.GitHub. [/Readarr/src/Readarr.sln]`

2) the Azure Pipelines fail


I can't figure out whether that has to do with the rebase and the removal of the line you suggested, or whether that's something else. 

Thoughts?

2025-01-09 20:11 UTC, mynameisbogdan commented on src/Readarr.Api.V1/Books/BookResource.cs
> +                LastSearchTime = resource.LastSearchTime
Thanks for reporting, fixed the warning. 

Please do another rebase and I'll check why the pipelines fail after.

2025-01-09 21:15 UTC, ManiMatter commented on src/Readarr.Api.V1/Books/BookResource.cs
> +                LastSearchTime = resource.LastSearchTime
Thanks for the fast fix, B. Rebased and the first error is gone. lets see where the azure pipelines take us.

2025-01-09 21:39 UTC, ManiMatter commented on src/Readarr.Api.V1/Books/BookResource.cs
> +                LastSearchTime = resource.LastSearchTime
and looks like the azure checks now also pass. thanks again for the review and swift fix.

2025-02-15 17:22 UTC, ManiMatter commented
@mynameisbogdan since the PR is still flagged as "changes requested" - just checking if there's anything pending on my end?

2025-02-16 15:55 UTC, merged

2025-02-16 15:56 UTC, mynameisbogdan commented
No, I just needed to test if the changes actually work for Readarr as I forgot if I cherry picked the 'LastSearchTime to be updated on search' commit.