New: Update all wiki links to point to the Servarr Wiki
Readarr/Readarr pull request #665
Opened 2020-12-20 22:36 UTC by bakerboy448

#### Database Migration
 NO

#### Description
Update links to use Servarr Wiki

#### Todos
- [X] Tests
- [ ] Wiki Updates - assigned to Drazz

#### Issues Fixed or Closed by this PR

* Fixes #656
* Fixes #653

2020-12-24 20:24 UTC, Qstick commented
Wanna update all the fragments in here

2021-01-21 23:16 UTC, bakerboy448 commented
Rebase after mega PR will be needed

2021-01-30 20:08 UTC, Qstick commented
@bakerboy448 rebase on develop please :)

2021-02-04 03:10 UTC, Qstick requested changes

2021-02-04 03:10 UTC, Qstick commented on src/NzbDrone.Core/HealthCheck/Checks/DotnetVersionCheck.cs
> +using System;
Why'd you add this back?

2021-02-04 03:16 UTC, Qstick commented on src/Readarr.Api.V1/ProviderResource.cs
> +                InfoLink = string.Format("https://wiki.servarr.com/Readarr_Supported-{0}",
should this be `"https://wiki.servarr.com/Readarr_Supported_{0}"`

2021-02-04 03:41 UTC, Qstick approved these changes

2021-02-04 03:42 UTC, merged